// client/src/pages/info.vue
<script lang="ts" setup>
const { t } = useI18n()
</script>

<template>
  <b-container p="6">
    <h1 class="display-4 mb-10">
      {{ t('info.creators.title') }}
    </h1>
    <b-row class="flex-column flex-md-row align-items-center" mb-4>
      <b-col cols="12" lg="6" mb-8>
        <b-row>
          <b-col cols="12" md="auto" class="mb-md-0 mr-md-6">
            <b-img lazy src="images/avatar1.jpg" alt="Avatar" rounded="circle" class="mb-md-0 avatar object-fit-cover mb-4" />
          </b-col>
          <b-col>
            <h1 class="display-4 mb-2">
              msan
            </h1>
            <p class="text-muted-foreground">
              {{ t('info.creators.first-description') }}
            </p>
            <p>
              Github: <a class="link" href="http://github.com/Megageorgio">{{ t('singer.siteLink') }}</a>
            </p>
          </b-col>
        </b-row>
      </b-col>
      <b-col cols="12" lg="6" mb-8>
        <b-row>
          <b-col cols="12" md="auto" class="mb-md-0 mr-md-6">
            <b-img lazy src="images/avatar2.jpg" alt="Avatar" rounded="circle" class="mb-md-0 avatar object-fit-cover mb-4" />
          </b-col>
          <b-col>
            <h1 class="display-4 mb-2">
              HHS_kt
            </h1>
            <p class="text-muted-foreground">
              {{ t('info.creators.second-description') }}
            </p>
            <p>
              Youtube: <a class="link" href="https://www.youtube.com/@HHS_kt">{{ t('singer.siteLink') }}</a>
            </p>
          </b-col>
        </b-row>
      </b-col>
    </b-row>

    <b-row class="mb-8">
      <h2 class="display-4 mb-4">
        {{ t('info.rules.title') }}
      </h2>
      <b-list-group>
        <b-list-group-item>
          {{ t('info.rules.no-prohibited-content') }}
        </b-list-group-item>
        <b-list-group-item>
          {{ t('info.rules.no-disinformation') }}
        </b-list-group-item>
        <b-list-group-item>
          {{ t('info.rules.no-repository-spam') }}
        </b-list-group-item>
        <b-list-group-item>
          {{ t('info.rules.no-tags-spam') }}
        </b-list-group-item>
      </b-list-group>
    </b-row>

    <b-row class="mb-4">
      <h2 class="display-4 mb-10">
        {{ t('info.videos.title') }}
      </h2>
      <b-col lg="6" cols-12 mb-8>
        <h4>{{ t('info.videos.first-name') }}</h4>
        <iframe
          class="card-shadow rounded-4"
          width="100%"
          height="315"
          src="https://www.youtube.com/embed/i1hXV4UWMyU"
          allowfullscreen
        />
      </b-col>
      <b-col lg="6" cols-12 mb-8>
        <h4>{{ t('info.videos.second-name') }}</h4>
        <iframe
          class="card-shadow rounded-4"
          width="100%"
          height="315"
          src="https://youtube.com/embed/qnUS5jaFu8c"
          allowfullscreen
        />
      </b-col>
    </b-row>
  </b-container>
</template>

<style scoped>
.carousel-inner img {
  width: 100%;
  height: auto;
}
.badge {
  margin: 2px;
  padding: 5px 15px;
}

.badge-language {
  background-color: #ff679d !important;
}

.badge-voicebank {
  background-color: #4ea6ea !important;
}
.embed-responsive {
  padding: 10px;
}

.card-shadow {
  box-shadow: 0 0.3rem 0.7rem rgba(0, 0, 0, 0.15);
}

.avatar {
  width: 200px;
  height: 200px;
}

.pic {
  cursor: pointer;
  transition:
    transform 0.3s ease-in-out,
    box-shadow 0.3s ease-in-out;
}

.pic:hover {
  transform: translateY(-7px);
  box-shadow: 0 6px 12px rgba(0, 0, 0, 0.2);
}

h3 {
  margin-bottom: 20px;
}
</style>

// src/routes/info/+page.svelte
<script lang="ts">
  import { t } from 'svelte-i18n';
  import { Card, Listgroup, ListgroupItem, Avatar } from 'flowbite-svelte';
  import { ShieldCheck, Info, Users } from 'lucide-svelte';
  import tilt from '@savy011/tilt-svelte';
</script>

<div class="max-w-4xl mx-auto space-y-16 pb-20">
  <section class="space-y-8">
    <h1 class="text-4xl font-black tracking-tight text-gray-900 dark:text-white flex items-center gap-4">
      <Users class="w-10 h-10 text-primary-600" /> {$t('info.creators.title')}
    </h1>
    
    <div class="grid grid-cols-1 md:grid-cols-2 gap-32">
      <Card class="border-none bg-gray-50 dark:bg-gray-800/50 rounded-3xl p-6" {@attach tilt({ max: 8 })}>
        <div class="flex items-center gap-6">
          <Avatar src="/images/avatar1.jpg" size="xl" class="aspect-square object-cover"/>
          <div class="space-y-1">
            <h3 class="text-2xl font-bold">msan</h3>
            <p class="text-gray-500 text-sm">{$t('info.creators.first-description')}</p>
            <a href="https://github.com/Megageorgio" target="_blank" class="text-primary-600 hover:underline text-sm font-medium">GitHub Profile</a>
          </div>
        </div>
      </Card>

      <Card class="border-none bg-gray-50 dark:bg-gray-800/50 rounded-3xl p-6" {@attach tilt({ max: 8 })}>
        <div class="flex items-center gap-6">
          <Avatar src="/images/avatar2.jpg" size="xl" class="aspect-square object-cover"/>
          <div class="space-y-1">
            <h3 class="text-2xl font-bold">HHS_kt</h3>
            <p class="text-gray-500 text-sm">{$t('info.creators.second-description')}</p>
            <a href="https://www.youtube.com/@HHS_kt" target="_blank" class="text-primary-600 hover:underline text-sm font-medium">YouTube Channel</a>
          </div>
        </div>
      </Card>
    </div>
  </section>

  <section class="space-y-8">
    <h2 class="text-3xl font-bold flex items-center gap-4">
      <ShieldCheck class="w-8 h-8 text-green-500" /> {$t('info.rules.title')}
    </h2>
    <Listgroup class="border-none bg-transparent space-y-3">
      <ListgroupItem class="bg-gray-50 dark:bg-gray-800/50 rounded-2xl border-none p-4">
        {$t('info.rules.no-prohibited-content')}
      </ListgroupItem>
      <ListgroupItem class="bg-gray-50 dark:bg-gray-800/50 rounded-2xl border-none p-4">
        {$t('info.rules.no-disinformation')}
      </ListgroupItem>
      <ListgroupItem class="bg-gray-50 dark:bg-gray-800/50 rounded-2xl border-none p-4">
        {$t('info.rules.no-repository-spam')}
      </ListgroupItem>
      <ListgroupItem class="bg-gray-50 dark:bg-gray-800/50 rounded-2xl border-none p-4">
        {$t('info.rules.no-tags-spam')}
      </ListgroupItem>
    </Listgroup>
  </section>

  <section class="space-y-8">
    <h2 class="text-3xl font-bold flex items-center gap-4">
      <Info class="w-8 h-8 text-blue-500" /> {$t('info.videos.title')}
    </h2>
    <div class="grid grid-cols-1 md:grid-cols-1 gap-8">
      <div class="space-y-4">
        <div class="aspect-video rounded-3xl overflow-hidden shadow-xl">
          <iframe width="100%" height="100%" title="Guide 2" src="https://youtube.com/embed/qnUS5jaFu8c" frameborder="0" allowfullscreen></iframe>
        </div>
      </div>
    </div>
  </section>
</div>
